-- create database hbtn_0d_usa
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- create table states in hbtn_0d_usa
-- attributs : id (unique autogenerated, not null, primary)
--              name VARCHAR
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states (
    id INT  auto_increment NOT NULL UNIQUE,
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
)