-- create database hbtn_0d_usa 
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- create table cities associated
-- attributs : id (int unique, autogenerated, cant null and primary key)
--             state_id (int, not null, foreign key)
--             name (varchar not null)
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities (
    id INT auto_increment NOT NULL UNIQUE,
    state_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id)
        REFERENCES  hbtn_0d_usa.states(id)
);